/**
 * Saasgrids CRM grid
 * Saasgrids CRM grid
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@saasgrids.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Call'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Call'));
  } else {
    // Browser globals (root is window)
    if (!root.crms) {
      root.crms = {};
    }
    root.crms.CallsApi = factory(root.crms.ApiClient, root.crms.Call);
  }
}(this, function(ApiClient, Call) {
  'use strict';

  /**
   * Calls service.
   * @module crms/CallsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new CallsApi. 
   * @alias module:crms/CallsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Creates a new call
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {module:model/Call} body Call object that needs to be created
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Call} and HTTP response
     */
    this.createCallWithHttpInfo = function(userId, body) {
      var postBody = body;

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling createCall");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createCall");
      }


      var pathParams = {
        'userId': userId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Call;

      return this.apiClient.callApi(
        '/{userId}/calls', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Creates a new call
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {module:model/Call} body Call object that needs to be created
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Call}
     */
    this.createCall = function(userId, body) {
      return this.createCallWithHttpInfo(userId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete call by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {String} callId ObjectId of call
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.deleteCallByIdWithHttpInfo = function(userId, callId) {
      var postBody = null;

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling deleteCallById");
      }

      // verify the required parameter 'callId' is set
      if (callId === undefined || callId === null) {
        throw new Error("Missing the required parameter 'callId' when calling deleteCallById");
      }


      var pathParams = {
        'userId': userId,
        'callId': callId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{userId}/calls/{callId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete call by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {String} callId ObjectId of call
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.deleteCallById = function(userId, callId) {
      return this.deleteCallByIdWithHttpInfo(userId, callId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get all calls
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {String} email Email id of the call
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Call>} and HTTP response
     */
    this.getAllCallsWithHttpInfo = function(userId, email) {
      var postBody = null;

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getAllCalls");
      }

      // verify the required parameter 'email' is set
      if (email === undefined || email === null) {
        throw new Error("Missing the required parameter 'email' when calling getAllCalls");
      }


      var pathParams = {
        'userId': userId
      };
      var queryParams = {
        'email': email
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Call];

      return this.apiClient.callApi(
        '/{userId}/calls', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get all calls
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {String} email Email id of the call
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Call>}
     */
    this.getAllCalls = function(userId, email) {
      return this.getAllCallsWithHttpInfo(userId, email)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get call by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {String} callId ObjectId of call
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Call} and HTTP response
     */
    this.getCallByIdWithHttpInfo = function(userId, callId) {
      var postBody = null;

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getCallById");
      }

      // verify the required parameter 'callId' is set
      if (callId === undefined || callId === null) {
        throw new Error("Missing the required parameter 'callId' when calling getCallById");
      }


      var pathParams = {
        'userId': userId,
        'callId': callId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Call;

      return this.apiClient.callApi(
        '/{userId}/calls/{callId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get call by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {String} callId ObjectId of call
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Call}
     */
    this.getCallById = function(userId, callId) {
      return this.getCallByIdWithHttpInfo(userId, callId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update call by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {module:model/Call} body Call object that needs to be updated
     * @param {String} callId ObjectId of call
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.updateCallByIdWithHttpInfo = function(userId, body, callId) {
      var postBody = body;

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling updateCallById");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateCallById");
      }

      // verify the required parameter 'callId' is set
      if (callId === undefined || callId === null) {
        throw new Error("Missing the required parameter 'callId' when calling updateCallById");
      }


      var pathParams = {
        'userId': userId,
        'callId': callId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{userId}/calls/{callId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Update call by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {module:model/Call} body Call object that needs to be updated
     * @param {String} callId ObjectId of call
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.updateCallById = function(userId, body, callId) {
      return this.updateCallByIdWithHttpInfo(userId, body, callId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
