/**
 * Saasgrids CRM grid
 * Saasgrids CRM grid
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@saasgrids.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Deal'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Deal'));
  } else {
    // Browser globals (root is window)
    if (!root.crms) {
      root.crms = {};
    }
    root.crms.DealsApi = factory(root.crms.ApiClient, root.crms.Deal);
  }
}(this, function(ApiClient, Deal) {
  'use strict';

  /**
   * Deals service.
   * @module crms/DealsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new DealsApi. 
   * @alias module:crms/DealsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Creates a new deals
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {module:model/Deal} body Deal object that needs to be created
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.createDealsWithHttpInfo = function(userId, body) {
      var postBody = body;

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling createDeals");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createDeals");
      }


      var pathParams = {
        'userId': userId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{userId}/deals', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Creates a new deals
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {module:model/Deal} body Deal object that needs to be created
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.createDeals = function(userId, body) {
      return this.createDealsWithHttpInfo(userId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Delete deal by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.deleteDealByIdWithHttpInfo = function(userId) {
      var postBody = null;

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling deleteDealById");
      }


      var pathParams = {
        'userId': userId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{userId}/deal/{dealId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Delete deal by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.deleteDealById = function(userId) {
      return this.deleteDealByIdWithHttpInfo(userId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get all deal
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {String} email Email id of the deal
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Deal>} and HTTP response
     */
    this.getAllDealWithHttpInfo = function(userId, email) {
      var postBody = null;

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getAllDeal");
      }

      // verify the required parameter 'email' is set
      if (email === undefined || email === null) {
        throw new Error("Missing the required parameter 'email' when calling getAllDeal");
      }


      var pathParams = {
        'userId': userId
      };
      var queryParams = {
        'email': email
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Deal];

      return this.apiClient.callApi(
        '/{userId}/deals', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get all deal
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {String} email Email id of the deal
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Deal>}
     */
    this.getAllDeal = function(userId, email) {
      return this.getAllDealWithHttpInfo(userId, email)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get deal by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {String} dealId ObjectId of acount
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Deal} and HTTP response
     */
    this.getDealByIdWithHttpInfo = function(userId, dealId) {
      var postBody = null;

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling getDealById");
      }

      // verify the required parameter 'dealId' is set
      if (dealId === undefined || dealId === null) {
        throw new Error("Missing the required parameter 'dealId' when calling getDealById");
      }


      var pathParams = {
        'userId': userId,
        'dealId': dealId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Deal;

      return this.apiClient.callApi(
        '/{userId}/deal/{dealId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Get deal by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {String} dealId ObjectId of acount
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Deal}
     */
    this.getDealById = function(userId, dealId) {
      return this.getDealByIdWithHttpInfo(userId, dealId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Update deal by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {module:model/Deal} body Deal object that needs to be updated
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    this.updateDealByIdWithHttpInfo = function(userId, body) {
      var postBody = body;

      // verify the required parameter 'userId' is set
      if (userId === undefined || userId === null) {
        throw new Error("Missing the required parameter 'userId' when calling updateDealById");
      }

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateDealById");
      }


      var pathParams = {
        'userId': userId
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['basicAuth'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/{userId}/deal/{dealId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Update deal by Id
     * 
     * @param {String} userId User instance id returned from saasgrids after authorization
     * @param {module:model/Deal} body Deal object that needs to be updated
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    this.updateDealById = function(userId, body) {
      return this.updateDealByIdWithHttpInfo(userId, body)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
