/**
 * Saasgrids CRM grid
 * Saasgrids CRM grid
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@saasgrids.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Account', 'model/Appointment', 'model/Call', 'model/Contact', 'model/Customfield', 'model/Deal', 'model/Email', 'model/Field', 'model/Filter', 'model/InlineResponse200', 'model/InlineResponse2001', 'model/InlineResponse2002', 'model/InlineResponse2003', 'model/InlineResponse2004', 'model/InlineResponse2005', 'model/InlineResponse2006', 'model/InlineResponse2007', 'model/Lead', 'model/Note', 'model/Task', 'model/User', 'crms/AccountsApi', 'crms/AppointmentsApi', 'crms/CallsApi', 'crms/ContactsApi', 'crms/DealsApi', 'crms/EmailsApi', 'crms/LeadsApi', 'crms/NotesApi', 'crms/TasksApi', 'crms/UsersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Account'), require('./model/Appointment'), require('./model/Call'), require('./model/Contact'), require('./model/Customfield'), require('./model/Deal'), require('./model/Email'), require('./model/Field'), require('./model/Filter'), require('./model/InlineResponse200'), require('./model/InlineResponse2001'), require('./model/InlineResponse2002'), require('./model/InlineResponse2003'), require('./model/InlineResponse2004'), require('./model/InlineResponse2005'), require('./model/InlineResponse2006'), require('./model/InlineResponse2007'), require('./model/Lead'), require('./model/Note'), require('./model/Task'), require('./model/User'), require('./crms/AccountsApi'), require('./crms/AppointmentsApi'), require('./crms/CallsApi'), require('./crms/ContactsApi'), require('./crms/DealsApi'), require('./crms/EmailsApi'), require('./crms/LeadsApi'), require('./crms/NotesApi'), require('./crms/TasksApi'), require('./crms/UsersApi'));
  }
}(function(ApiClient, Account, Appointment, Call, Contact, Customfield, Deal, Email, Field, Filter, InlineResponse200, InlineResponse2001, InlineResponse2002, InlineResponse2003, InlineResponse2004, InlineResponse2005, InlineResponse2006, InlineResponse2007, Lead, Note, Task, User, AccountsApi, AppointmentsApi, CallsApi, ContactsApi, DealsApi, EmailsApi, LeadsApi, NotesApi, TasksApi, UsersApi) {
  'use strict';

  /**
   * Saasgrids_CRM_grid.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var crms = require('index'); // See note below*.
   * var xxxSvc = new crms.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new crms.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new crms.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new crms.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Account model constructor.
     * @property {module:model/Account}
     */
    Account: Account,
    /**
     * The Appointment model constructor.
     * @property {module:model/Appointment}
     */
    Appointment: Appointment,
    /**
     * The Call model constructor.
     * @property {module:model/Call}
     */
    Call: Call,
    /**
     * The Contact model constructor.
     * @property {module:model/Contact}
     */
    Contact: Contact,
    /**
     * The Customfield model constructor.
     * @property {module:model/Customfield}
     */
    Customfield: Customfield,
    /**
     * The Deal model constructor.
     * @property {module:model/Deal}
     */
    Deal: Deal,
    /**
     * The Email model constructor.
     * @property {module:model/Email}
     */
    Email: Email,
    /**
     * The Field model constructor.
     * @property {module:model/Field}
     */
    Field: Field,
    /**
     * The Filter model constructor.
     * @property {module:model/Filter}
     */
    Filter: Filter,
    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200: InlineResponse200,
    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001: InlineResponse2001,
    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002: InlineResponse2002,
    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003: InlineResponse2003,
    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004: InlineResponse2004,
    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005: InlineResponse2005,
    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006: InlineResponse2006,
    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007: InlineResponse2007,
    /**
     * The Lead model constructor.
     * @property {module:model/Lead}
     */
    Lead: Lead,
    /**
     * The Note model constructor.
     * @property {module:model/Note}
     */
    Note: Note,
    /**
     * The Task model constructor.
     * @property {module:model/Task}
     */
    Task: Task,
    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User: User,
    /**
     * The AccountsApi service constructor.
     * @property {module:crms/AccountsApi}
     */
    AccountsApi: AccountsApi,
    /**
     * The AppointmentsApi service constructor.
     * @property {module:crms/AppointmentsApi}
     */
    AppointmentsApi: AppointmentsApi,
    /**
     * The CallsApi service constructor.
     * @property {module:crms/CallsApi}
     */
    CallsApi: CallsApi,
    /**
     * The ContactsApi service constructor.
     * @property {module:crms/ContactsApi}
     */
    ContactsApi: ContactsApi,
    /**
     * The DealsApi service constructor.
     * @property {module:crms/DealsApi}
     */
    DealsApi: DealsApi,
    /**
     * The EmailsApi service constructor.
     * @property {module:crms/EmailsApi}
     */
    EmailsApi: EmailsApi,
    /**
     * The LeadsApi service constructor.
     * @property {module:crms/LeadsApi}
     */
    LeadsApi: LeadsApi,
    /**
     * The NotesApi service constructor.
     * @property {module:crms/NotesApi}
     */
    NotesApi: NotesApi,
    /**
     * The TasksApi service constructor.
     * @property {module:crms/TasksApi}
     */
    TasksApi: TasksApi,
    /**
     * The UsersApi service constructor.
     * @property {module:crms/UsersApi}
     */
    UsersApi: UsersApi
  };

  return exports;
}));
