/**
 * Saasgrids CRM grid
 * Saasgrids CRM grid
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@saasgrids.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.crms);
  }
}(this, function(expect, crms) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new crms.ContactsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContactsApi', function() {
    describe('createContact', function() {
      it('should call createContact successfully', function(done) {
        //uncomment below and update the code to test createContact
        //instance.createContact(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteContactById', function() {
      it('should call deleteContactById successfully', function(done) {
        //uncomment below and update the code to test deleteContactById
        //instance.deleteContactById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContactByFilter', function() {
      it('should call getContactByFilter successfully', function(done) {
        //uncomment below and update the code to test getContactByFilter
        //instance.getContactByFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContactById', function() {
      it('should call getContactById successfully', function(done) {
        //uncomment below and update the code to test getContactById
        //instance.getContactById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContactFilters', function() {
      it('should call getContactFilters successfully', function(done) {
        //uncomment below and update the code to test getContactFilters
        //instance.getContactFilters(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContactProperties', function() {
      it('should call getContactProperties successfully', function(done) {
        //uncomment below and update the code to test getContactProperties
        //instance.getContactProperties(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContacts', function() {
      it('should call getContacts successfully', function(done) {
        //uncomment below and update the code to test getContacts
        //instance.getContacts(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getContactsByEmail', function() {
      it('should call getContactsByEmail successfully', function(done) {
        //uncomment below and update the code to test getContactsByEmail
        //instance.getContactsByEmail(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateContactById', function() {
      it('should call updateContactById successfully', function(done) {
        //uncomment below and update the code to test updateContactById
        //instance.updateContactById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
