/**
 * Saasgrids CRM grid
 * Saasgrids CRM grid
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hello@saasgrids.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.crms);
  }
}(this, function(expect, crms) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new crms.LeadsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LeadsApi', function() {
    describe('createLead', function() {
      it('should call createLead successfully', function(done) {
        //uncomment below and update the code to test createLead
        //instance.createLead(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteLeadById', function() {
      it('should call deleteLeadById successfully', function(done) {
        //uncomment below and update the code to test deleteLeadById
        //instance.deleteLeadById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getAllLeads', function() {
      it('should call getAllLeads successfully', function(done) {
        //uncomment below and update the code to test getAllLeads
        //instance.getAllLeads(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLeadById', function() {
      it('should call getLeadById successfully', function(done) {
        //uncomment below and update the code to test getLeadById
        //instance.getLeadById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLeadFilters', function() {
      it('should call getLeadFilters successfully', function(done) {
        //uncomment below and update the code to test getLeadFilters
        //instance.getLeadFilters(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getLeadsByFilter', function() {
      it('should call getLeadsByFilter successfully', function(done) {
        //uncomment below and update the code to test getLeadsByFilter
        //instance.getLeadsByFilter(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLeadById', function() {
      it('should call updateLeadById successfully', function(done) {
        //uncomment below and update the code to test updateLeadById
        //instance.updateLeadById(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
